// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_i03TZUrJLPq77hBzE0Sla9odLP3d_k',
    appId: '1:730716051485:web:5119f106f0e1161ab2cef4',
    messagingSenderId: '730716051485',
    projectId: 'bd-gerenciador-r',
    authDomain: 'bd-gerenciador-r.firebaseapp.com',
    storageBucket: 'bd-gerenciador-r.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB61e48bCSjLKCB7PIS6LvAaA8quU3ZEA',
    appId: '1:730716051485:android:15045391d75941b1b2cef4',
    messagingSenderId: '730716051485',
    projectId: 'bd-gerenciador-r',
    storageBucket: 'bd-gerenciador-r.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_RSXc06Lj2uvBuh_Y8X6d786E-VTMWg',
    appId: '1:730716051485:ios:bd59d522c265472cb2cef4',
    messagingSenderId: '730716051485',
    projectId: 'bd-gerenciador-r',
    storageBucket: 'bd-gerenciador-r.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_RSXc06Lj2uvBuh_Y8X6d786E-VTMWg',
    appId: '1:730716051485:ios:bd59d522c265472cb2cef4',
    messagingSenderId: '730716051485',
    projectId: 'bd-gerenciador-r',
    storageBucket: 'bd-gerenciador-r.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
